services:
    sonata.admin.partner:
        class: ProjetNormandie\PartnerBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "PartnerBundle", label: "Partner" }
        arguments:
            - ~
            - ProjetNormandie\PartnerBundle\Entity\Partner
            - ~

