services:
    sonata.admin.partner:
        class: ProjetNormandie\PartnerBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, model_class: 'ProjetNormandie\PartnerBundle\Entity\Partner', manager_type: orm, group: "group.partners", label: "label.partner" }
        arguments: [ ~, ~, ~ ]

